theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 研究生

# 对你自己的简洁描述
description: 认真，数理基础好

# 你的美照地址
logo: /assets/images/MyPicture.jpeg

# 你的名字
name: 胡哲玮

# 你的联系方式
phone: 18671989896

# 你的邮箱
email: U202213821@hust.edu.cn

# 你目前的住址
address: 湖北武汉

# 你毕业院校
school: 华中科技大学

# 你的专业
profession: 电子信息工程（信息类数理提高班）

# 你的学位
degree: 本科在读（2022届）

# 你获得过的证书或奖励
credential: 计算机网络技术三级证书、英语六级证书

# 你的政治身份
political: 中共预备党员
