theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 前端开发工程师

# 对你自己的简洁描述
description: 开朗，幽默，自信，爱阅读和运动

# 你的美照地址
logo: /assets/images/wangjianing.jpg

# 你的名字
name: 王佳宁(Mica Red)

# 你的联系方式
phone: 15024063193

# 你的邮箱
email: jianingw321@outlook.com

# 你目前的住址
address: 广东东莞

# 你毕业院校
school: 对外经济贸易大学

# 你的专业
profession: 国际经济与贸易/西班牙语

# 你的学位
degree: 本科（2021届）

# 你获得过的证书或奖励
credential: 雅思7.0
